name: Atria

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Atria
    runs-on: macos-15

    steps:
      - name: Checkout Atria
        uses: actions/checkout@v4
        with:
          path: main

      - name: dependencies
        run: brew install make ldid curl

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos ~/theos
          cd ~/theos
          curl -sSL https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS16.5.sdk.tar.xz | tar -xJv -C ~/theos/sdks
          chmod +x ./bin/install-theos
          ./bin/install-theos

      - name: Build deb
        run: |
          export THEOS=~/theos THEOS_PACKAGE_SCHEME=rootless
          cd main
          "$(brew --prefix make)/bin/gmake" clean package FINALPACKAGE=1

      - uses: actions/upload-artifact@v4
        with:
          name: Atria deb
          path: main/packages/*.deb
